# Site settings
baseweb: "" # the subpath of your site, e.g. /blog
web: "" # the base hostname & protocol for your site
collections:
  work:
    output: true
defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: work
      header-text: white
      weight: 5

# Build settings
markdown: kramdown
plugins:
   - jemoji
   - jekyll-redirect-from

# Metadata
keywords: "web developer, designer, philadelphia"

# Third party services
# google-fonts: "Source+Sans+Pro:400,700,900"
# google-fonts-subsets: "latin"
google-analytics: "UA-33381009-6"
typekit: "xmd5huf"

# Commonly used lingo
title: "Victor âœ¨"
location: "Philadelphia, PA, USA"
email: contact@example.com
description: > # this means to ignore newlines until the next colon
  Hey there! I'm a interactive digital experience designer and developer from Philly!
handle: pixelyunicorn

# Offline debug flag
dev: false

# Flag that does the thing
melody: false